# Generated by Django 2.0.2 on 2021-04-17 23:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user_profile',
            name='email',
        ),
        migrations.RemoveField(
            model_name='user_profile',
            name='lname',
        ),
        migrations.RemoveField(
            model_name='user_profile',
            name='technologies',
        ),
    ]
