# Generated by Django 2.0.2 on 2021-04-18 04:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0002_auto_20210417_2350'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_profile',
            name='grade',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='user_profile',
            name='save_file',
            field=models.FileField(default=None, upload_to='uploads/%Y/%m/%d/'),
        ),
    ]
