# Generated by Django 2.0.2 on 2021-04-20 01:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0008_auto_20210420_0114'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_profile',
            name='fname',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='login.User'),
        ),
    ]
