# Generated by Django 3.2 on 2021-04-21 22:46

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0011_auto_20210420_0139'),
    ]

    operations = [
        migrations.CreateModel(
            name='School',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=300)),
                ('phone', models.CharField(blank=True, max_length=17, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in the format: '+123456789'. Up to 11 digits allowed.", regex='^\\+?1?\\d{10,11}$')])),
                ('city', models.CharField(blank=True, max_length=50)),
                ('zipcode', models.CharField(blank=True, max_length=5)),
            ],
        ),
        migrations.RenameField(
            model_name='user_profile',
            old_name='display_picture',
            new_name='upload_file',
        ),
        migrations.RemoveField(
            model_name='user_profile',
            name='fname',
        ),
        migrations.RemoveField(
            model_name='user_profile',
            name='save_file',
        ),
        migrations.AddField(
            model_name='user_profile',
            name='email',
            field=models.CharField(blank=True, max_length=300),
        ),
        migrations.AddField(
            model_name='user_profile',
            name='gender',
            field=models.CharField(blank=True, choices=[('m', 'male'), ('f', 'female'), ('n', 'not applicable')], default='n', max_length=1),
        ),
        migrations.AddField(
            model_name='user_profile',
            name='name',
            field=models.CharField(blank=True, max_length=300),
        ),
        migrations.AddField(
            model_name='user_profile',
            name='phone',
            field=models.CharField(blank=True, max_length=11, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in the format: '+123456789'. Up to 11 digits allowed.", regex='^\\+?1?\\d{10,11}$')]),
        ),
        migrations.AddField(
            model_name='user_profile',
            name='responsibility',
            field=models.CharField(blank=True, choices=[('t', 'Teacher'), ('m', 'Manager'), ('o', 'other')], default='t', max_length=1),
        ),
        migrations.AddField(
            model_name='user_profile',
            name='school',
            field=models.ForeignKey(blank=True, default=None, on_delete=django.db.models.deletion.CASCADE, to='login.school'),
        ),
    ]
