# Generated by Django 3.2 on 2021-04-22 02:36

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0012_auto_20210421_2246'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user_profile',
            old_name='name',
            new_name='first_name',
        ),
        migrations.RenameField(
            model_name='user_profile',
            old_name='responsibility',
            new_name='role',
        ),
        migrations.RemoveField(
            model_name='user_profile',
            name='upload_file',
        ),
        migrations.AddField(
            model_name='user_profile',
            name='last_name',
            field=models.CharField(blank=True, max_length=300),
        ),
        migrations.AlterField(
            model_name='school',
            name='city',
            field=models.CharField(blank=True, help_text='city name, eg. College Station', max_length=50),
        ),
        migrations.AlterField(
            model_name='school',
            name='name',
            field=models.CharField(help_text='first name, middle and family name, eg. First Middle Family', max_length=300),
        ),
        migrations.AlterField(
            model_name='school',
            name='phone',
            field=models.CharField(blank=True, help_text="Phone number must be entered in the format: '+123456789'. Up to 11 digits allowed.", max_length=17, validators=[django.core.validators.RegexValidator(message="Phone number must starts with +1 and in the format: '+12345678900'. Up to 12 digits allowed.", regex='^\\+?1?\\d{10,15}$')]),
        ),
        migrations.AlterField(
            model_name='school',
            name='zipcode',
            field=models.CharField(blank=True, help_text='five digits, eg. 12345', max_length=5),
        ),
        migrations.AlterField(
            model_name='user_profile',
            name='school',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='login.school'),
        ),
        migrations.CreateModel(
            name='SavedFile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('upload_file', models.FileField(upload_to='')),
                ('user_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='login.user_profile')),
            ],
        ),
    ]
