# Generated by Django 3.2 on 2021-04-22 03:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0014_auto_20210422_0301'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='savedfile',
            name='save_file',
        ),
    ]
