# Generated by Django 3.2 on 2021-04-22 03:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0015_remove_savedfile_save_file'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user_profile',
            name='school',
        ),
        migrations.DeleteModel(
            name='School',
        ),
    ]
