# Generated by Django 2.2.14 on 2021-05-02 17:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='File',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(choices=[('READING_SPANISH', 'Reading-Spanish'), ('READING_ENGLISH', 'Reading-English'), ('MATH', 'Math')], default=None, max_length=25)),
                ('grade', models.CharField(choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('6', '6'), ('7', '7'), ('8', '8'), ('9', '9'), ('10', '10'), ('11', '11'), ('12', '12')], default=None, max_length=2)),
                ('upload_file', models.FileField(blank=True, default=None, null=True, upload_to='uploads/%Y/%m/%d/', verbose_name='file_name')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='file_owner', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
