# Generated by Django 2.2.14 on 2021-07-17 21:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('file_upload', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='file',
            name='grade',
        ),
        migrations.RemoveField(
            model_name='file',
            name='subject',
        ),
        migrations.RemoveField(
            model_name='file',
            name='upload_file',
        ),
    ]
