# Generated by Django 2.2.14 on 2021-08-19 21:16

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('file_upload', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='fileinfo',
            name='file_id',
            field=models.UUIDField(default=uuid.uuid4, editable=False),
        ),
    ]
