# Generated by Django 2.2.14 on 2021-07-17 21:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('file_upload', '0002_auto_20210717_1601'),
    ]

    operations = [
        migrations.CreateModel(
            name='File_Info',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document_id', models.CharField(max_length=50)),
                ('original_file_name', models.CharField(max_length=50)),
                ('grade', models.CharField(max_length=50)),
                ('subject', models.CharField(max_length=50)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='file_owner', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.DeleteModel(
            name='File',
        ),
    ]
