# Generated by Django 2.2.14 on 2021-07-18 15:16

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('file_upload', '0003_auto_20210717_1647'),
    ]

    operations = [
        migrations.AddField(
            model_name='file_info',
            name='creation_date',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
