# Generated by Django 2.2.14 on 2021-07-18 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('file_upload', '0004_file_info_creation_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file_info',
            name='creation_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
