# Generated by Django 2.2.14 on 2021-08-18 20:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import dspp.storage_backends


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('file_upload', '0005_auto_20210718_1018'),
    ]

    operations = [
        migrations.CreateModel(
            name='FileInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(storage=dspp.storage_backends.PrivateMediaStorage(), upload_to='')),
                ('file_name', models.CharField(max_length=50)),
                ('grade', models.CharField(max_length=50)),
                ('subject', models.CharField(max_length=50)),
                ('creation_date', models.DateTimeField(auto_now_add=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='file_owner', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.DeleteModel(
            name='File_Info',
        ),
    ]
