# Generated by Django 2.2.14 on 2021-08-18 20:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('file_upload', '0006_auto_20210818_1427'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fileinfo',
            name='creation_date',
        ),
        migrations.RemoveField(
            model_name='fileinfo',
            name='file_name',
        ),
        migrations.RemoveField(
            model_name='fileinfo',
            name='grade',
        ),
        migrations.RemoveField(
            model_name='fileinfo',
            name='owner',
        ),
        migrations.RemoveField(
            model_name='fileinfo',
            name='subject',
        ),
    ]
