# Generated by Django 2.2.14 on 2021-08-18 20:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('file_upload', '0007_auto_20210818_1439'),
    ]

    operations = [
        migrations.AddField(
            model_name='fileinfo',
            name='creation_date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='fileinfo',
            name='file_name',
            field=models.CharField(default=django.utils.timezone.now, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='fileinfo',
            name='grade',
            field=models.CharField(default='3', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='fileinfo',
            name='owner',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='file_owner', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='fileinfo',
            name='subject',
            field=models.CharField(default='math', max_length=50),
            preserve_default=False,
        ),
    ]
