# Generated by Django 2.2.14 on 2021-08-18 21:45

from django.db import migrations, models
import dspp.storage_backends


class Migration(migrations.Migration):

    dependencies = [
        ('file_upload', '0009_auto_20210818_1507'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fileinfo',
            name='file',
            field=models.FileField(storage=dspp.storage_backends.PrivateMediaStorage(), upload_to=''),
        ),
    ]
