# Generated by Django 2.2.14 on 2021-08-18 22:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('file_upload', '0010_auto_20210818_1545'),
    ]

    operations = [
        migrations.RenameField(
            model_name='fileinfo',
            old_name='file_name',
            new_name='document_id',
        ),
        migrations.RemoveField(
            model_name='fileinfo',
            name='file',
        ),
        migrations.AddField(
            model_name='fileinfo',
            name='file_path',
            field=models.CharField(default=123, max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='fileinfo',
            name='original_file_name',
            field=models.CharField(default='test123', max_length=50),
            preserve_default=False,
        ),
    ]
