# Generated by Django 2.2.14 on 2021-08-18 23:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('file_upload', '0011_auto_20210818_1620'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fileinfo',
            name='document_id',
        ),
        migrations.RemoveField(
            model_name='fileinfo',
            name='original_file_name',
        ),
        migrations.AddField(
            model_name='fileinfo',
            name='file_name',
            field=models.TextField(default='default_file.csv'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='fileinfo',
            name='file_path',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='fileinfo',
            name='grade',
            field=models.CharField(max_length=2),
        ),
        migrations.AlterField(
            model_name='fileinfo',
            name='subject',
            field=models.CharField(max_length=25),
        ),
    ]
